### ISSUE TITLE
Instalate Linux

### ISSUE THREAD

**Issue by RogueRebel** [mentecatoDev/DAW1#2]

**Comment by RogueRebel** [comment]
https://www.ionos.es/digitalguide/servidores/know-how/linux-vs-windows-el-gran-cuadro-comparativo/#:~:text=Mientras%20que%20Windows%20ofrece%20funciones,sistema%20de%20gesti%C3%B3n%20de%20contenidos.

**Comment by mentecatoDev** [comment]
Ni loco
